/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConexionSQL.conexion;
import Datos.*;
import Textos.Textos;
import java.awt.Color;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author EMPRESA
 */
public class Egreso extends javax.swing.JFrame {
private Egresos Dats;
private Caja caj;

    public Egreso() {
        initComponents();
        this.setLocationRelativeTo(null);
        Dats=new Egresos();
        caj=new Caja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        Ta_Descripción = new javax.swing.JTextArea();
        Tf_Fecha = new javax.swing.JTextField();
        TF_VT = new javax.swing.JTextField();
        Tf_Valor = new javax.swing.JTextField();
        BTN_Volver = new javax.swing.JButton();
        BTN_guardar = new javax.swing.JButton();
        BTN_FechaAuto = new javax.swing.JButton();
        Label_fondo = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Egresos");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ta_Descripción.setBackground(new Color(0,0,0,0));
        Ta_Descripción.setColumns(20);
        Ta_Descripción.setFont(new java.awt.Font("Bebas Neue", 0, 22)); // NOI18N
        Ta_Descripción.setRows(5);
        Ta_Descripción.setBorder(null);
        Ta_Descripción.setOpaque(false);
        jPanel2.add(Ta_Descripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 660, 160));

        Tf_Fecha.setBackground(new Color(0,0,0,0));
        Tf_Fecha.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Tf_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        Tf_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_Fecha.setToolTipText("");
        Tf_Fecha.setBorder(null);
        Tf_Fecha.setCaretColor(new java.awt.Color(255, 255, 255));
        Tf_Fecha.setOpaque(false);
        Tf_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_FechaActionPerformed(evt);
            }
        });
        jPanel2.add(Tf_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 200, 20));

        TF_VT.setBackground(new Color(0,0,0,0));
        TF_VT.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        TF_VT.setForeground(new java.awt.Color(0, 0, 0));
        TF_VT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_VT.setBorder(null);
        TF_VT.setOpaque(false);
        TF_VT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_VTActionPerformed(evt);
            }
        });
        jPanel2.add(TF_VT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 194, 380, -1));

        Tf_Valor.setBackground(new Color(0,0,0,0));
        Tf_Valor.setFont(new java.awt.Font("Bebas Neue", 0, 34)); // NOI18N
        Tf_Valor.setForeground(new java.awt.Color(0, 0, 0));
        Tf_Valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_Valor.setBorder(null);
        Tf_Valor.setCaretColor(new java.awt.Color(0, 153, 153));
        Tf_Valor.setOpaque(false);
        Tf_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tf_ValorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tf_ValorKeyTyped(evt);
            }
        });
        jPanel2.add(Tf_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 250, 30));

        BTN_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón volver.png"))); // NOI18N
        BTN_Volver.setBorder(null);
        BTN_Volver.setContentAreaFilled(false);
        BTN_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Volver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón volver ON.png"))); // NOI18N
        BTN_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_VolverActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 50));

        BTN_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón guardar.png"))); // NOI18N
        BTN_guardar.setBorder(null);
        BTN_guardar.setContentAreaFilled(false);
        BTN_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón guardar ON.png"))); // NOI18N
        BTN_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón guardar ON.png"))); // NOI18N
        BTN_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 50));

        BTN_FechaAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón fechaauto.png"))); // NOI18N
        BTN_FechaAuto.setBorder(null);
        BTN_FechaAuto.setContentAreaFilled(false);
        BTN_FechaAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_FechaAuto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón fechaauto ON.png"))); // NOI18N
        BTN_FechaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FechaAutoActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_FechaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 255, 150, 30));

        Label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo egreso.png"))); // NOI18N
        jPanel2.add(Label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    int valorS;
   
    
    
    
    private void limpiar(){

Tf_Valor.setText("");
Tf_Fecha.setText("");
TF_VT.setText("");
Ta_Descripción.setText("");

}
    private void BTN_FechaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FechaAutoActionPerformed
     Date date = new Date();  
     DateFormat HoraFechaFormat = new SimpleDateFormat("h:mm a - dd/MM/YYYY"); //  YYYY - MM - DD HH: MM: SS
     
      
   
     Tf_Fecha.setText(HoraFechaFormat.format(date));   
    
      
        
        
    }//GEN-LAST:event_BTN_FechaAutoActionPerformed

    private void Tf_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_FechaActionPerformed

    private void BTN_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_guardarActionPerformed
/*ConexionSQL.conexion c =new conexion();
c.getConnection();*/
int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de crear este reporte?");
if (resp==0) {
        int valor= valorS;
        String Descripción= Ta_Descripción.getText();
        String V_T= TF_VT.getText();
        String Fecha= Tf_Fecha.getText();
        
        Dats.InsertarIngreso(valor, Descripción, V_T, Fecha);
        caj.ObtenerDatos();
        int Saldoac = Integer.parseInt(caj.obtenerTextInfo("Saldo"));
        int egreso = Saldoac-valor;
        caj.ActualizarCaja(Integer.toString(egreso));
        System.out.println("Todo bien todo correcto");
        limpiar();
}

    }//GEN-LAST:event_BTN_guardarActionPerformed

    private void TF_VTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_VTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_VTActionPerformed

    private void BTN_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VolverActionPerformed
Inicio inicio= new Inicio();
inicio.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_VolverActionPerformed

    private void Tf_ValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_ValorKeyTyped
        Textos t = new Textos();
        t.Snumeros(evt);
    }//GEN-LAST:event_Tf_ValorKeyTyped

    private void Tf_ValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_ValorKeyReleased
 DecimalFormat df = new DecimalFormat("#,###");
        valorS =Integer.parseInt(Tf_Valor.getText().replace(".", ""));
        if (Tf_Valor.getText().length() >= 1) {
 
            Tf_Valor.setText( df.format(Integer.valueOf(Tf_Valor.getText().replace(".", "").replace(",", ""))) );}
    }//GEN-LAST:event_Tf_ValorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Egreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Egreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_FechaAuto;
    private javax.swing.JButton BTN_Volver;
    private javax.swing.JButton BTN_guardar;
    private javax.swing.JLabel Label_fondo;
    private javax.swing.JTextField TF_VT;
    private javax.swing.JTextArea Ta_Descripción;
    private javax.swing.JTextField Tf_Fecha;
    private javax.swing.JTextField Tf_Valor;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
