/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import ConexionSQL.conexion;
import Datos.Caja;
import Datos.Ingresos;
import Textos.Textos;
import java.awt.Color;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author EMPRESA
 */
public class Ingreso extends javax.swing.JFrame {

    private Ingresos Dat;
    private Caja caj;

    public Ingreso() {
        initComponents();
        this.setLocationRelativeTo(null);
        limpiar();
        ganancia();
        Dat = new Ingresos();
        caj = new Caja();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btn_Calcular = new javax.swing.JButton();
        Label_Ganancia = new javax.swing.JLabel();
        Ta_Descripción = new javax.swing.JTextArea();
        Tf_Pago = new javax.swing.JTextField();
        Tf_Costo = new javax.swing.JTextField();
        Tf_Fecha = new javax.swing.JTextField();
        TF_VT = new javax.swing.JTextField();
        Tf_Valor = new javax.swing.JTextField();
        BTN_Volver = new javax.swing.JButton();
        BTN_guardar = new javax.swing.JButton();
        BTN_FechaAuto = new javax.swing.JButton();
        Label_fondo = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingresos");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 40));

        Btn_Calcular.setText("Calcular");
        Btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CalcularActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, -1, -1));

        Label_Ganancia.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Label_Ganancia.setForeground(new java.awt.Color(0, 0, 0));
        Label_Ganancia.setText("0");
        jPanel2.add(Label_Ganancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 316, 140, 30));

        Ta_Descripción.setBackground(new Color(0,0,0,0));
        Ta_Descripción.setColumns(20);
        Ta_Descripción.setFont(new java.awt.Font("Bebas Neue", 0, 22)); // NOI18N
        Ta_Descripción.setRows(5);
        Ta_Descripción.setBorder(null);
        Ta_Descripción.setOpaque(false);
        jPanel2.add(Ta_Descripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 690, 130));

        Tf_Pago.setBackground(new Color(0,0,0,0));
        Tf_Pago.setFont(new java.awt.Font("Bebas Neue", 0, 34)); // NOI18N
        Tf_Pago.setForeground(new java.awt.Color(0, 0, 0));
        Tf_Pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_Pago.setBorder(null);
        Tf_Pago.setCaretColor(new java.awt.Color(0, 153, 153));
        Tf_Pago.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Tf_Pago.setOpaque(false);
        Tf_Pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tf_PagoMouseClicked(evt);
            }
        });
        Tf_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_PagoActionPerformed(evt);
            }
        });
        Tf_Pago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tf_PagoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tf_PagoKeyTyped(evt);
            }
        });
        jPanel2.add(Tf_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 191, 250, 35));

        Tf_Costo.setBackground(new Color(0,0,0,0));
        Tf_Costo.setFont(new java.awt.Font("Bebas Neue", 0, 34)); // NOI18N
        Tf_Costo.setForeground(new java.awt.Color(0, 0, 0));
        Tf_Costo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_Costo.setBorder(null);
        Tf_Costo.setCaretColor(new java.awt.Color(0, 153, 153));
        Tf_Costo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Tf_Costo.setOpaque(false);
        Tf_Costo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tf_CostoMouseClicked(evt);
            }
        });
        Tf_Costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_CostoActionPerformed(evt);
            }
        });
        Tf_Costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tf_CostoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tf_CostoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tf_CostoKeyTyped(evt);
            }
        });
        jPanel2.add(Tf_Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 114, 213, 30));

        Tf_Fecha.setBackground(new Color(0,0,0,0));
        Tf_Fecha.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        Tf_Fecha.setForeground(new java.awt.Color(0, 0, 0));
        Tf_Fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_Fecha.setToolTipText("");
        Tf_Fecha.setBorder(null);
        Tf_Fecha.setCaretColor(new java.awt.Color(255, 255, 255));
        Tf_Fecha.setOpaque(false);
        Tf_Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_FechaActionPerformed(evt);
            }
        });
        jPanel2.add(Tf_Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 260, 30));

        TF_VT.setBackground(new Color(0,0,0,0));
        TF_VT.setFont(new java.awt.Font("Bebas Neue", 0, 26)); // NOI18N
        TF_VT.setForeground(new java.awt.Color(0, 0, 0));
        TF_VT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TF_VT.setBorder(null);
        TF_VT.setOpaque(false);
        jPanel2.add(TF_VT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 230, -1));

        Tf_Valor.setBackground(new Color(0,0,0,0));
        Tf_Valor.setFont(new java.awt.Font("Bebas Neue", 0, 34)); // NOI18N
        Tf_Valor.setForeground(new java.awt.Color(0, 0, 0));
        Tf_Valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Tf_Valor.setBorder(null);
        Tf_Valor.setCaretColor(new java.awt.Color(0, 153, 153));
        Tf_Valor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Tf_Valor.setOpaque(false);
        Tf_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf_ValorActionPerformed(evt);
            }
        });
        Tf_Valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Tf_ValorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Tf_ValorKeyTyped(evt);
            }
        });
        jPanel2.add(Tf_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 250, 30));

        BTN_Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón volver.png"))); // NOI18N
        BTN_Volver.setBorder(null);
        BTN_Volver.setContentAreaFilled(false);
        BTN_Volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_Volver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón volver ON.png"))); // NOI18N
        BTN_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_VolverActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 130, 50));

        BTN_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón guardar.png"))); // NOI18N
        BTN_guardar.setBorder(null);
        BTN_guardar.setContentAreaFilled(false);
        BTN_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_guardar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón guardar ON.png"))); // NOI18N
        BTN_guardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón guardar ON.png"))); // NOI18N
        BTN_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 120, 50));

        BTN_FechaAuto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón fechaauto.png"))); // NOI18N
        BTN_FechaAuto.setBorder(null);
        BTN_FechaAuto.setContentAreaFilled(false);
        BTN_FechaAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_FechaAuto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón fechaauto ON.png"))); // NOI18N
        BTN_FechaAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FechaAutoActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_FechaAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 150, 30));

        Label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Fondo ingreso 3_1.png"))); // NOI18N
        jPanel2.add(Label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    private void rellenar() {

       System.out.println("ESTAMOS EN RELLENAR");
        System.out.println("EL VALOR DEL TF ES:"+Tf_Valor.getText()+" FIN");
        
        
        if (Tf_Valor.getText().length() == 0 ) {
            Tf_Valor.setText("0");
        }
        if (Tf_Pago.getText().length() == 0) {
            Tf_Pago.setText("0");
        }
        if (Tf_Costo.getText().length() == 0) {
            Tf_Costo.setText("0");
        }

        System.out.println("Interfaces.Ingreso.rellenar()");

    }

    private void limpiar() {

        Tf_Valor.setText("0");
        Tf_Fecha.setText("");
        TF_VT.setText("");
        Ta_Descripción.setText("");
        Tf_Costo.setText("0");
        Tf_Pago.setText("0");

    }
    int valorS;
    int Costo;
    int PagoT;
    int Ganancia;

    private int calcular() {

        int pagoauto = (valorS - Costo) / 2;

        return pagoauto;

    }

    private void ganancia() {

        Costo = Integer.parseInt(Tf_Costo.getText());
        PagoT = Integer.parseInt(Tf_Pago.getText());
        Ganancia = (valorS - Costo - PagoT);
        String Gananciatxt = Integer.toString(Ganancia);



        Label_Ganancia.setText(Gananciatxt);

    }


    private void BTN_FechaAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FechaAutoActionPerformed
        Date date = new Date();
        DateFormat HoraFechaFormat = new SimpleDateFormat("h:mm a - dd/MM/YYYY");
        Tf_Fecha.setText(HoraFechaFormat.format(date));


    }//GEN-LAST:event_BTN_FechaAutoActionPerformed

    private void Tf_FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_FechaActionPerformed

    private void BTN_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_guardarActionPerformed
        rellenar();
        ganancia();
        calcular();
        ganancia();

        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de crear este reporte?");
        if (resp == 0) {

            String Descripción = Ta_Descripción.getText();
            String V_T = TF_VT.getText();
            String Fecha = Tf_Fecha.getText();
            String tiempo;
            Dat.InsertarIngreso(valorS, Costo, PagoT, Ganancia, Descripción, V_T, Fecha);
            caj.ObtenerDatos();

            int Saldoac = Integer.parseInt(caj.obtenerTextInfo("Saldo"));
            System.out.println("saldo actual= " + Saldoac);
            int ingreso = Saldoac + Ganancia;
            caj.ActualizarCaja(Integer.toString(ingreso));

            System.out.println("Todo bien todo correcto");
            limpiar();
}

    }//GEN-LAST:event_BTN_guardarActionPerformed

    private void BTN_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VolverActionPerformed
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_VolverActionPerformed

    private void Tf_ValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_ValorKeyTyped
        Textos t = new Textos();
        t.Snumeros(evt);
        
       
        
        
        
        
    }//GEN-LAST:event_Tf_ValorKeyTyped

    private void Tf_ValorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_ValorKeyReleased
 DecimalFormat df = new DecimalFormat("#,###");
        valorS =Integer.parseInt(Tf_Valor.getText().replace(".", ""));
        if (Tf_Valor.getText().length() >= 1) {
 
            Tf_Valor.setText( df.format(Integer.valueOf(Tf_Valor.getText().replace(".", "").replace(",", ""))) );
        }else{
      
        }
        

        
    }//GEN-LAST:event_Tf_ValorKeyReleased

    private void Tf_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_ValorActionPerformed

    private void Tf_CostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_CostoActionPerformed





    }//GEN-LAST:event_Tf_CostoActionPerformed

    private void Tf_CostoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_CostoKeyReleased
   
        /*  DecimalFormat df = new DecimalFormat("#,###");
        Costo =Integer.parseInt(Tf_Costo.getText().replace(".", ""));
        if (Tf_Costo.getText().length() >= 1) {
 
            Tf_Costo.setText( df.format(Integer.valueOf(Tf_Costo.getText().replace(".", "").replace(",", ""))) );
        }else{
      
        }*/
        

        
        
      
        
        
    }//GEN-LAST:event_Tf_CostoKeyReleased

    private void Tf_CostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_CostoKeyTyped


        Textos t = new Textos();
        t.Snumeros(evt);



    }//GEN-LAST:event_Tf_CostoKeyTyped

    private void Tf_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf_PagoActionPerformed




    }//GEN-LAST:event_Tf_PagoActionPerformed

    private void Tf_PagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_PagoKeyTyped



    }//GEN-LAST:event_Tf_PagoKeyTyped

    private void Tf_CostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tf_CostoMouseClicked





    }//GEN-LAST:event_Tf_CostoMouseClicked

    private void Tf_PagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tf_PagoMouseClicked



    }//GEN-LAST:event_Tf_PagoMouseClicked

    private void Btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CalcularActionPerformed

        rellenar();
        ganancia();
        calcular();
        ganancia();
        




    }//GEN-LAST:event_Btn_CalcularActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      
        
        
        rellenar();
        ganancia();
        Tf_Pago.setText(Integer.toString(calcular()));
        ganancia();
        

        
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void Tf_PagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_PagoKeyReleased

        

       


    }//GEN-LAST:event_Tf_PagoKeyReleased

    private void Tf_CostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_CostoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf_CostoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_FechaAuto;
    private javax.swing.JButton BTN_Volver;
    private javax.swing.JButton BTN_guardar;
    private javax.swing.JButton Btn_Calcular;
    private javax.swing.JLabel Label_Ganancia;
    private javax.swing.JLabel Label_fondo;
    private javax.swing.JTextField TF_VT;
    private javax.swing.JTextArea Ta_Descripción;
    private javax.swing.JTextField Tf_Costo;
    private javax.swing.JTextField Tf_Fecha;
    private javax.swing.JTextField Tf_Pago;
    private javax.swing.JTextField Tf_Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
