/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Datos.*;
import java.awt.Color;
import java.awt.DefaultFocusTraversalPolicy;
import java.awt.Font;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

/**
 *
 * @author EMPRESA
 */
public class Inicio extends javax.swing.JFrame {

private Caja caj;
DefaultTableModel model;
 private Ingresos Dat;
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        caj= new Caja();
        Dat = new Ingresos();
        try {
            fechaactual();
            Cargarcaja();
           //  cargarEgresos();
             cargarIngresos();
        } catch (Exception e) {
            System.err.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopMenuTabla = new javax.swing.JPopupMenu();
        MenuBorrar = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        T_ingresos = new javax.swing.JTable();
        BTN_ingreso = new javax.swing.JButton();
        Btn_Admin = new javax.swing.JButton();
        Label_Saldo = new javax.swing.JLabel();
        Label_fondo = new javax.swing.JLabel();

        MenuBorrar.setBackground(new java.awt.Color(255, 102, 102));
        MenuBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MenuBorrar.setForeground(new java.awt.Color(255, 255, 255));
        MenuBorrar.setText("Borrar");
        MenuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBorrarActionPerformed(evt);
            }
        });
        PopMenuTabla.add(MenuBorrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N

        T_ingresos.setBackground(new java.awt.Color(255, 255, 255));
        T_ingresos.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        T_ingresos.setComponentPopupMenu(PopMenuTabla);
        T_ingresos.setDoubleBuffered(true);
        T_ingresos.setDragEnabled(false);
        T_ingresos.setEditingColumn(0);
        T_ingresos.setEditingRow(0);
        T_ingresos.setFocusable(false);
        T_ingresos.setGridColor(new java.awt.Color(255, 255, 255));
        T_ingresos.setSelectionBackground(new java.awt.Color(0, 153, 153));
        T_ingresos.setSelectionForeground(new java.awt.Color(255, 255, 0));
        T_ingresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                T_ingresosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(T_ingresos);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 750, 170));

        BTN_ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón Ingreso.png"))); // NOI18N
        BTN_ingreso.setBorder(null);
        BTN_ingreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTN_ingreso.setOpaque(false);
        BTN_ingreso.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Botón Ingreso ON.png"))); // NOI18N
        BTN_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ingresoActionPerformed(evt);
            }
        });
        jPanel2.add(BTN_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 230, 50));

        Btn_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Btn Admin.png"))); // NOI18N
        Btn_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AdminActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 80));

        Label_Saldo.setBackground(new java.awt.Color(183, 238, 195));
        Label_Saldo.setFont(new java.awt.Font("Bebas Neue", 0, 38)); // NOI18N
        Label_Saldo.setForeground(new java.awt.Color(53, 173, 88));
        Label_Saldo.setText("0");
        jPanel2.add(Label_Saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, -1, -1));

        Label_fondo.setBackground(new java.awt.Color(255, 255, 255));
        Label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Interfaz inicio 2.png"))); // NOI18N
        jPanel2.add(Label_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 800, 740));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String Fecha;

    public void borrarregistro() {

        try {

            int id = Integer.parseInt(selecitem(7));
            int ganancia = Integer.parseInt(selecitem(3).replace("$ ", ""));

            int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este ingreso?");
            if (resp == 0) {

                caj.ObtenerDatos();

                int Saldoac = Integer.parseInt(caj.obtenerTextInfo("Saldo"));
                System.out.println("saldo actual= " + Saldoac);
                int ingreso = Saldoac - ganancia;

                caj.ActualizarCaja(Integer.toString(ingreso));
                Dat.Eliminaringreso(id);
                Cargarcaja();
                cargarIngresos();

            }
        } catch (HeadlessException | NumberFormatException e) {

            System.out.println("el eerror al dar borrar es : " + e);
        }


 
 }   
void Cargarcaja(){
    DecimalFormat df = new DecimalFormat("#,###");
    caj.ObtenerDatos();
        
        String saldo= caj.obtenerTextInfo("Saldo");
        int saldo2= Integer.parseInt(saldo);
        Label_Saldo.setText("$ "+df.format(saldo2));
        char simbol = saldo.charAt(0);
        if (simbol=='-') {
            Label_Saldo.setForeground(Color.red);
     
     

        }

}
void fechaactual(){

     Date date = new Date();  
    DateFormat FechaFormat; FechaFormat = new SimpleDateFormat("dd/MM/YYYY"); 
    Fecha = FechaFormat.format(date);
}



 String selecitem(int dato){

 DefaultTableModel t = (DefaultTableModel) T_ingresos.getModel();
int fselec= T_ingresos.getSelectedRow();
String valor = t.getValueAt(fselec, dato).toString();

return valor;

}
    
void cargarIngresos(){

Ingresos a = new Ingresos();
a.tablaFecha(Fecha);
T_ingresos.setModel(a.model);

JTableHeader th; 
th = T_ingresos.getTableHeader();
th.setForeground(Color.BLACK);
Font fuente = new Font("Bebas Neue", Font.PLAIN, 18);  
th.setFont(fuente); 
th.setForeground(Color.WHITE);
th.setBackground(new Color(199,226,123));
    


}    
    private void BTN_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ingresoActionPerformed


Ingreso ingreso= new Ingreso();
ingreso.setVisible(true);
this.setVisible(false);



    }//GEN-LAST:event_BTN_ingresoActionPerformed

    private void Btn_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AdminActionPerformed
 //String contraseña = JOptionPane.showInputDialog( "Cual es su nombre?" );
this.setVisible(false);
 
Login l =new Login();
l.setVisible(true);





    }//GEN-LAST:event_Btn_AdminActionPerformed

    private void T_ingresosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_T_ingresosMouseClicked







    }//GEN-LAST:event_T_ingresosMouseClicked

    private void MenuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBorrarActionPerformed




        borrarregistro();
    

        


    }//GEN-LAST:event_MenuBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ingreso;
    private javax.swing.JButton Btn_Admin;
    private javax.swing.JLabel Label_Saldo;
    private javax.swing.JLabel Label_fondo;
    private javax.swing.JMenuItem MenuBorrar;
    private javax.swing.JPopupMenu PopMenuTabla;
    private javax.swing.JTable T_ingresos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
