/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.event.KeyEvent;

/**
 *
 * @author EMPRESA
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Error = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Pf_Contraseña = new javax.swing.JPasswordField();
        Btn_Cancelar = new javax.swing.JButton();
        Btn_Entrar = new javax.swing.JButton();

        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Error.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        Label_Error.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(Label_Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Por favor ingrese la contraseña:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        Pf_Contraseña.setBackground(new java.awt.Color(255, 255, 255));
        Pf_Contraseña.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Pf_Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Pf_Contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(Pf_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 210, -1));

        Btn_Cancelar.setBackground(new java.awt.Color(255, 153, 153));
        Btn_Cancelar.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Btn_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Cancelar.setText("Cancelar");
        Btn_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CancelarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        Btn_Entrar.setBackground(new java.awt.Color(204, 255, 204));
        Btn_Entrar.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        Btn_Entrar.setForeground(new java.awt.Color(51, 51, 51));
        Btn_Entrar.setText("Entrar");
        Btn_Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EntrarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public String Contraseña= "clrodriguez65";
    private void enter(){
        
        String ContraIn = Pf_Contraseña.getText();

if (ContraIn.equals(Contraseña)) {
    System.out.println("Contraseña correcta");

caja caja =new caja();
caja.setVisible(true);
this.setVisible(false);
        }else{
System.out.println("Contraseña incorrecta");
Label_Error.setText("Contraseña incorrecta");
}
        
    }   
    
    
    private void Btn_EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EntrarActionPerformed


enter();




    }//GEN-LAST:event_Btn_EntrarActionPerformed

    private void Btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CancelarActionPerformed
Inicio i = new Inicio();
this.setVisible(false);
i.setVisible(true);
    }//GEN-LAST:event_Btn_CancelarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

                if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                    enter();
                }

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancelar;
    private javax.swing.JButton Btn_Entrar;
    private javax.swing.JLabel Label_Error;
    private javax.swing.JPasswordField Pf_Contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
